services:
  - type: web
    name: eventease-backend
    rootDir: eventease
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    env: java
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
